### ISSUE TITLE
Raspberry pi Zero (not 2) error

### ISSUE THREAD

**Issue by D20180** [heneault/cubotino#1]
Followed AndreaFavero step 1-3

uname -a returns
Linux rubik 5.10.103+ #1529 Tue Mar 8 12:19:18 GMT 2022 armv**6**l GNU/Linux

script errors out @ 

  Downloading https://www.piwheels.org/simple/opencv-contrib-python/opencv_contrib_python-4.1.0.25-cp37-cp37m-linux_armv6l.whl (15.1MB)
    100% |████████████████████████████████| 15.1MB 5.3kB/s
THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    opencv-contrib-python==4.1.0.25 from https://www.piwheels.org/simple/opencv-contrib-python/opencv_contrib_python-4.1.0.25-cp37-cp37m-linux_armv6l.whl#sha256=954a9148b4da078697e62c93b64aa5697155698c2757ae37278b3013a7a60cae:
        Expected sha256 954a9148b4da078697e62c93b64aa5697155698c2757ae37278b3013a7a60cae
             Got        ddf3ab7b2295eb96e0bd2b1b31d0517b7597e916081a298297512922beffd90b

**Comment by heneault** [comment]
I implemented a workaround in the setup script to download that file directly and bypass the bad index
